/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class datasignals_m2g_M2G */

#ifndef _Included_datasignals_m2g_M2G
#define _Included_datasignals_m2g_M2G
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      datasignals_m2g_M2G
 * Method:     connect
 * Signature:  (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_datasignals_m2g_M2G_connect
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:      datasignals_m2g_M2G
 * Method:     disconnect
 * Signature:  (I)I
 */
JNIEXPORT jint JNICALL Java_datasignals_m2g_M2G_disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:      datasignals_m2g_M2G
 * Method:     write
 * Signature:  (I[BII)I
 */
JNIEXPORT jint JNICALL Java_datasignals_m2g_M2G_write
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:      datasignals_m2g_M2G
 * Method:     read
 * Signature:  (I[BII)I
 */
JNIEXPORT jint JNICALL Java_datasignals_m2g_M2G_read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:      datasignals_m2g_M2G
 * Method:     byteCount
 * Signature:  (I)I
 */
JNIEXPORT jint JNICALL Java_datasignals_m2g_M2G_byteCount
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
