/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class datasignals_transform_matrix_jni_JNativeMatrixMixer */

#ifndef _Included_datasignals_transform_matrix_jni_JNativeMatrixMixer
#define _Included_datasignals_transform_matrix_jni_JNativeMatrixMixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      datasignals_transform_matrix_jni_JNativeMatrixMixer
 * Method:     mix
 * Signature:  ([BI[JI[[B[II)V
 */
JNIEXPORT void JNICALL Java_datasignals_transform_matrix_jni_JNativeMatrixMixer_mix
  (JNIEnv *, jclass, jbyteArray, jint, jlongArray, jint, jobjectArray, jintArray, jint);

/*
 * Class:      datasignals_transform_matrix_jni_JNativeMatrixMixer
 * Method:     concurrentMix
 * Signature:  ([BI[JI[[B[III)V
 */
JNIEXPORT void JNICALL Java_datasignals_transform_matrix_jni_JNativeMatrixMixer_concurrentMix
  (JNIEnv *, jclass, jbyteArray, jint, jlongArray, jint, jobjectArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
