/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class datasignals_transform_matrix_jni_JNativeMatrixSplitter */

#ifndef _Included_datasignals_transform_matrix_jni_JNativeMatrixSplitter
#define _Included_datasignals_transform_matrix_jni_JNativeMatrixSplitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      datasignals_transform_matrix_jni_JNativeMatrixSplitter
 * Method:     split
 * Signature:  ([[B[I[JI[BII)V
 */
JNIEXPORT void JNICALL Java_datasignals_transform_matrix_jni_JNativeMatrixSplitter_split
  (JNIEnv *, jclass, jobjectArray, jintArray, jlongArray, jint, jbyteArray, jint, jint);

/*
 * Class:      datasignals_transform_matrix_jni_JNativeMatrixSplitter
 * Method:     concurrentSplit
 * Signature:  ([[B[I[JI[BIII)V
 */
JNIEXPORT void JNICALL Java_datasignals_transform_matrix_jni_JNativeMatrixSplitter_concurrentSplit
  (JNIEnv *, jclass, jobjectArray, jintArray, jlongArray, jint, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
